### ISSUE TITLE
Flatten Stage

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-reactive-streams#100]
We discussed the interface Stage, which is huge and contains so many nested interfaces. I think it makes sense to flatten the hierarchy.

**Comment by jroper** [comment]
One advantage of not flattening it is that it makes it much easier to implement, because Java doesn't support relative package references or package aliases.

Let's say I have a Reactive Streams implementation that already defines classes like `Map` and `Filter` etc. Due to the name conflict, I'm going to have to refer to one of them by fully qualify class names, which is going to make the code ugly and verbose. But, if they are all inner classes, then I'm fine, I can just import the outer class, and refer to them using `Stage.Map`, `Stage.Filter` etc.

The issue is that there are a *lot* of classes here, and more to come, and the way these classes are used is that they tend to all be imported into the one class at once. It just introduces such a huge surface area for ugly name conflicts requiring fully qualified references. Given the usage pattern, it's much cleaner to group them in one class where they can be referenced through a relative reference to the outer class, and I think that makes it easier to read to because you can instantly see where the class has come from when reading the code, you know that it's one of the stages and not something else, you lose this if you flatten it.

**Comment by jroper** [comment]
As decided in the weekly hangout, we're not going to do this.
