### ISSUE TITLE
The tck has an unsatisifed dependnecy on reactive-streams-examples

### ISSUE THREAD

**Issue by benjamin-confino** [eclipse/microprofile-reactive-streams#101]
ReactiveStreamsArquillianTck places the package `org.reactivestreams.tck` and it's subpackages into the test war. That will create a dependency on reactive-streams-examples. 

For example `org.reactivestreams.tck.flow.support.HelperPublisher` imports `org.reactivestreams.example.unicast.AsyncIterablePublisher`

**Comment by jroper** [comment]
Thanks, in my own testing, I was adding the MicroProfile Reactive Streams Operators implementation dynamically using Arquillian (since I didn't have a container that supported it out of the box), and had an archive appender with this line:

```java
.addPackages(true, org.reactivestreams.Publisher.class.getPackage())
```

Which would have caused the recursive adding of the `reactive-streams-examples` package. Are you able to work around to verify whether there are any other dependencies that are missing?
