### ISSUE TITLE
Add support for @Produces?

### ISSUE THREAD

**Issue by cescoffier** [eclipse/microprofile-reactive-streams#72]
In the Reactive Messaging spec, it could be interesting to add the support for `@Produces` annotation:

```
@Produces
@Named("my-stream")
public PublisherBuilder<String> produceAStreamOfString() {
   // ....
}
```

Can be supported:

* `Publisher` (or sub-classes), `PublisherBuilder`
* `Subscriber` (or sub-classes), `SubscriberBuilder`

The `@Named` annotation is used to indicate the name that can be used in the `@Incoming` and `@Outgoing` annotations)

**Comment by jroper** [comment]
I think it would be worth discussing with some CDI people here - I wonder if that's not abusing the way CDI is meant to work - if you `@Produces` a `Subscriber` with a particular name, is it right/wrong for the container to decide to do something with that bean? It feels wrong for me, since you haven't anywhere explicitly told the container "hey I want you to plumb this subscriber to a topic with this name", you've just provided a named bean to the container for injection.

**Comment by cescoffier** [comment]
I discussed it with @antoinesd. It was fine, but better double check.

**Comment by Emily-Jiang** [comment]
I agree with James. @Named is for a bean to be used in jsp el. I think it
is very confusing to use it as a topic name.

**Comment by cescoffier** [comment]
So maybe we can introduce another annotation instead of `Name`. We can reuse `Outgoing` and `Incoming`.

**Comment by Emily-Jiang** [comment]
Marking a method with `@Produces` makes the method to be a producer, which produces a bean for injection. what is your use case to use this bean together with `Incoming` or `Outgoing`?

**Comment by cescoffier** [comment]
I find it pretty convenient to declare `Publisher` and `Subscriber` that would be used in the different method used annotated with `@Outgoing` and `@Incoming`.  I could do that with a method returning a subscriber or publisher, but I've found this way a bit more convenient.

**Comment by jroper** [comment]
Migrated to https://github.com/eclipse/microprofile-reactive-messaging/issues/9.
